//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASWODespatchMetrics
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class reportThas01Entities : DbContext
    {
        public reportThas01Entities()
            : base("name=reportThas01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<THAS_CONNECT_DespatchSeats_Result> THAS_CONNECT_DespatchSeats()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_DespatchSeats_Result>("THAS_CONNECT_DespatchSeats");
        }
    
        public virtual ObjectResult<THAS_CONNECT_VSWOThroughput_Result> THAS_CONNECT_VSWOThroughput()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_VSWOThroughput_Result>("THAS_CONNECT_VSWOThroughput");
        }
    }
}
