//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASWODespatchMetrics
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatThroughputHourlyResultSet
    {
        public long SeatThroughput_ID { get; set; }
        public string WorksOrderNumber { get; set; }
        public string CommercialNote { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string PartNumber { get; set; }
        public string PartDescription { get; set; }
        public int PaxCount { get; set; }
        public string Batch { get; set; }
        public string BatchLocation { get; set; }
        public string CurrentBatchLocation { get; set; }
        public string Username { get; set; }
        public string MethodType { get; set; }
        public string DefaultLocationCode { get; set; }
        public string ProductGroupCode { get; set; }
        public string RespCode { get; set; }
    }
}
